apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-backend
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      containers:
      - name: flask-backend
        # JENKINS WILL DYNAMICALLY MODIFY THIS EXACT LINE
        image: rahamshaik/flask-backend:v1.0.11
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
